# Generated by Django 4.1.2 on 2022-10-30 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('user_username', models.CharField(max_length=200)),
                ('user_fname', models.CharField(max_length=16)),
                ('user_lname', models.CharField(max_length=16)),
            ],
        ),
    ]
