# Generated by Django 4.1.2 on 2022-11-16 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_first_name', models.CharField(max_length=30)),
                ('user_last_name', models.CharField(max_length=30)),
                ('user_email', models.EmailField(max_length=50)),
                ('user_login', models.CharField(max_length=30)),
                ('user_password', models.CharField(max_length=20)),
                ('user_phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Deceased',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deceased_first_name', models.CharField(max_length=30)),
                ('deceased_last_name', models.CharField(max_length=30)),
                ('deceased_gender', models.CharField(max_length=1)),
                ('deceased_birth_date', models.DateField(help_text="Deceased's birthday")),
                ('deceased_birth_city', models.CharField(max_length=30)),
                ('deceased_birth_state', models.CharField(max_length=30)),
                ('deceased_birth_country', models.CharField(max_length=30)),
                ('deceased_death_date', models.DateField(help_text="Deceased's deathday")),
                ('deceased_death_city', models.CharField(max_length=30)),
                ('deceased_death_state', models.CharField(max_length=30)),
                ('deceased_death_country', models.CharField(max_length=30)),
                ('deceased_biography', models.CharField(max_length=20000)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.user')),
            ],
        ),
    ]
