# Generated by Django 4.1.2 on 2022-12-13 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deceased',
            name='profile_picture',
            field=models.ImageField(upload_to='profile_images'),
        ),
    ]
