# Generated by Django 4.1.2 on 2022-12-12 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=15)),
                ('birth_day', models.DateField()),
                ('birth_city', models.CharField(max_length=50)),
                ('birth_state', models.CharField(max_length=50)),
                ('birth_country', models.CharField(max_length=50)),
                ('death_day', models.DateField()),
                ('death_city', models.CharField(max_length=50)),
                ('death_state', models.CharField(max_length=50)),
                ('death_country', models.CharField(max_length=50)),
                ('bio', models.TextField()),
            ],
        ),
    ]
