# Generated by Django 4.1.2 on 2022-12-13 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_deceased_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deceased',
            name='profile_picture',
            field=models.ImageField(upload_to='profile_picture'),
        ),
    ]
