# Generated by Django 4.1.2 on 2022-12-13 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_deceased_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deceased',
            name='profile_picture',
        ),
    ]
