# Generated by Django 4.1.2 on 2022-12-13 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_biography'),
        ('pages', '0004_remove_deceased_profile_picture'),
    ]

    operations = [
    ]
