# Generated by Django 4.1.2 on 2022-12-13 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_merge_20221213_1733'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Biography',
        ),
        migrations.RemoveField(
            model_name='deceased',
            name='created_by',
        ),
        migrations.AddField(
            model_name='deceased',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.user'),
        ),
    ]
